config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  get '/users/search', to: 'users#search'
  resources :messages
  resources :groups, only: %i(index new create edit update) do
    resources :messages, only: %i(index create)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :messages
  has_many :users, through: :user_groups
  has_many :user_groups
  accepts_nested_attributes_for :user_groups
  validates :name, presence: true

  def last_message
    messages.present? ? messages.last.body : 'メッセージがありません'
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group
  validates :body, presence: true
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :messages
  has_many :groups, through: :user_groups
  has_many :user_groups
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys:[:name])
  end

  def set_group
    @group =  Group.find(params[:id])
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group , only: %i(edit update)

  def index
    @groups = current_user.groups
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: "グループが作成されました。"
    else
      redirect_to new_group_path , alert: "グループ名を入力してください。"
    end
  end

  def edit
  end

  def update
    @group.update(group_params)
    redirect_to group_messages_path(@group), notice: "チャットグループが編集されました"
  end

  private
  def group_params
    params.require(:group).permit(:name, {user_ids: []})
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group , only: %i(index create)
  before_action :set_message , only: %i(index create)

  def index
    @message = current_user.messages.new
    respond_to do |format|
      format.html { render :index }
      format.json {
        messageArray = []
        @messages.each do |message|
          messageArray << {
            body: message.body,
            name: message.user.name,
            image: message.image.url,
            created_at: message.created_at.strftime("%Y/%m/%d %H:%M:%S")
          }
        end
        render json: { message: messageArray }
      }
    end
  end

  def create
    @message = current_user.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.html { redirect_to group_messages_path(@group), notice: "メッセージを投稿しました。" }
        format.json { render json: {
              body: @message.body,
              name: @message.user.name,
              image: @message.image.url,
              created_at: @message.created_at.strftime("%Y/%m/%d %H:%M:%S")
            }
          }
      end
    else
      flash.now[:alert] = "メッセージを入力してください。"
      render "index"
    end

  end

  private
  def message_params
    params.require(:message).permit(:body, :image).merge(group_id: params[:group_id])
  end

  def set_group
    @group =  Group.find(params[:group_id])
    @groups = current_user.groups
  end

  def set_message
    @messages = @group.messages.includes(:user)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def search
    @users = User.where('name LIKE ?', "%#{params[:keyword]}%")
    respond_to do |format|
      format.json { render json: @users}
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/_chatside.html.haml
.chat-side
  .chat-user.clearfix
    %h5= current_user.name
    .chat-user__actions
      = link_to new_group_path, class: "chat-user__action" do
        %i.icon.fa.fa-pencil-square-o
      = link_to edit_user_registration_path, class: "chat-user__action" do
        %i.icon.fa.fa-cog
  %ul.chat-groups
    = render @groups

app/views/groups/_form.html.haml
= form_for @group, html: { id: "new_chat_group", class: "new_chat_group" } do |f|
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :name,"グループ名", class: "chat-group-form__label"
    .chat-group-form__field--right
      = f.text_field:name,placeholder:"グループ名を入力してください", id: "chat_group_name",class: "chat-group-form__input"
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :name, "チャットメンバーを追加", class: "chat-group-form__label"
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        %input.chat-group-form__input#user-search-field{ placeholder: "追加したいユーザー名を入力してください", type: "text" }
      #user-search-result
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :name,"チャットメンバー", class: "chat-group-form__label"
    .chat-group-form__field--right
      #chat-group-users
        .chat-group-user.clearfix
          = hidden_field_tag 'group[user_ids][]', current_user.id
          %p.chat-group-user__name
            = current_user.name
        -@group.users.each do |user|
          -if(user.id != current_user.id)
            .chat-group-user.clearfix
              = hidden_field_tag 'group[user_ids][]', user.id
              %p.chat-group-user__name=user.name
              = content_tag "a", '削除', class:"user-search-remove chat-group-user__btn chat-group-user__btn--remove", data: { user: { id:user.id }}
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit "Save", class: "chat-group-form__action-btn", data:{ disable_with: "Save" }

app/views/groups/_group.html.haml
%li.chat-group
  = link_to group_messages_path(group), class: 'chat-group__link' do
    %p.chat-group__name= group.name
    %p.chat-group__message= group.last_message

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  =render partial:"form"

app/views/groups/index.html.haml
.chat.clearfix
  = render partial: "groups/chatside"

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  - if @group.errors.any?
    #error_explanation
      %h2= @group.errors.full_messages
  =render partial:"form"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %p.notice
      = notice
    %p.alert
      = alert
    = yield

app/views/messages/_message.html.haml
%li.chat-message
  .chat-message__header.clearfix
    %p.chat-message__name
      = message.user.name
    %p.chat-message__time
      = l message.created_at, format: :default
  %p.chat-message__body
    = message.body
    - if message.image.present?
      %br
      = image_tag(message.image)

app/views/messages/index.html.haml
.chat.clearfix
  = render partial: "groups/chatside"

  .chat-main
    .chat-header.clearfix
      .chat-header--left
        %h2= @group.name
        %p.chat-header__users
          Members:
          -@group.users.each do |user|
            %span.chat-header__user= user.name
      .chat-header--right
        = link_to edit_group_path(params[:group_id]) do
          .chat-header__edit-btn Edit

    .chat-body
      %ul.chat-messages
        =render @messages

    .chat-footer
      = form_for [@group, @message] do |f|
        .chat-footer__body
          = f.text_area :body, placeholder: "type a message", rows: "1", id: "message_body"
          %label.chat-footer__image
            = f.file_field :image, class: "file_attach"
            %i.fa.fa-image
        = f.submit "SEND"